# fly.toml app configuration file generated for pixa-observe on 2024-11-11T00:27:55-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "${FLY_APP_NAME}"
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-2x'
  memory = '4gb'
  cpus = 2
