# fly.toml app configuration file generated for pixa-observe on 2024-11-11T00:27:55-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "APP_NAME_PLACEHOLDER"
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-2x'
  memory = '4gb'
  cpus = 2

[env]
  HOST = "0.0.0.0"
  PORT = "3003"
  ENVIRONMENT = "development"
  DEBUG = "true"
  AWS_BUCKET_NAME = "newmark"
  AWS_BUCKET_REGION = "us-east-1"
  AUDIO_SERVICE_URL = "https://api.pixa.dev"
  GOOGLE_APPLICATION_CREDENTIALS = "./gcp-credentials.json"
  GOOGLE_CLOUD_BUCKET_NAME = "pixa-audio"
