# fly.toml app configuration file generated for fixa-transcription-service-staging on 2024-11-20T23:20:05-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fixa-transcription-service-staging'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'performance-1x'
