# fly.toml app configuration file generated for pixa-observe on 2024-11-11T00:27:55-08:00
# redeploy
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pixa-observe"
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'performance-2x'
  memory = '4gb'
  cpus = 2

  [env]
    HOST = "0.0.0.0"
    PORT = "3003"
    AWS_BUCKET_NAME = "newmark"
    AWS_BUCKET_REGION = "us-east-1"
    GOOGLE_CLOUD_BUCKET_NAME = "pixa-audio"

