# ffmpeg_fmp4_command = [
#     'ffmpeg',
#     '-y',
#     # '-hwaccel', 'cuda',
#     '-f', 'rawvideo',
#     '-vcodec', 'rawvideo',
#     '-pix_fmt', 'rgba',
#     '-r', str(self.frame_rate),
#     '-s', f'{self.frame_width}x{self.frame_height}',
#     '-i', '-',
#     '-vf', 'vflip',
#     '-c:v', 'libx264', 

#     # '-level:v', '4.0',
#     # '-crf', '23',

#     # '-crf', '23',
#     # '-crf', '23',
#     # '-preset', 'veryfast',
    
#     # '-preset', 'ultrafast',
#     # '-tune', 'zerolatency',
#     '-b:v', '2M', 
#     '-maxrate', '2.5M',
#     '-bufsize', '4M',
#     '-g', '20',
#     '-f', 'hls',
#     '-hls_time', '0.5',
#     '-hls_segment_type', 'fmp4',
#     '-hls_fmp4_init_filename', 'init.mp4',
#     '-hls_list_size', '0',
#     '-hls_playlist_type', 'event',
#     '-hls_segment_filename', os.path.join(output_dir_str, 'stream%03d.m4s'),
#     os.path.join(output_dir_str, 'playlist.m3u8')
# ]