# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# 420 69

name: Fly Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-node-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          export FLY_APP_NAME=${{ github.ref == 'refs/heads/main' && 'pixa-observe' || 'pixa-observe-staging' }}
          flyctl deploy --remote-only --app $FLY_APP_NAME --dockerfile apps/node-server/Dockerfile --config apps/node-server/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-transcription-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          export FLY_APP_NAME=${{ github.ref == 'refs/heads/main' && 'fixa-transcription-service' || 'fixa-transcription-service-staging' }}
          cd apps/transcription-service
          flyctl deploy --remote-only --app $FLY_APP_NAME
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
